apiVersion: batch/v1
kind: Job
metadata:
  name: init-orders
spec:
  template:
    spec:
      containers:
        - name: init
          image: postgres:15
          command:
            - sh
            - -c
            - >
              psql postgresql://postgres:postgres@postgres:5432/postgres -c
              "CREATE TABLE IF NOT EXISTS orders (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL, book_id VARCHAR(50) NOT NULL, qty INTEGER NOT NULL DEFAULT 1, status VARCHAR(50) NOT NULL DEFAULT 'CREATED', created_at TIMESTAMP DEFAULT current_timestamp);"
      restartPolicy: Never
  backoffLimit: 1