apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  # keep defaults here; these will be read by the container as env
  PORT: "5000"
  # DATABASE_URL will be constructed from secret (see deployment)